### ISSUE TITLE
Will not start on server

### ISSUE THREAD

**Issue by RotokEralil** [mrsterner/GuardVillagers#1] opened 2022-01-25 02:13 UTC
I added the mod and started a new world on my server, and keeps crashing from the start.
I have no issues with it on my own PC in single player.
Server log while trying to start new world
[latest.log](https://github.com/mrsterner/GuardVillagers/files/7930098/latest.log)

**Comment by JoelZBub** [comment] 2022-01-27 03:27
trying to load client EntityModelLayer class on server.

**Comment by mrsterner** [comment] 2022-02-04 11:48
Ill look into it, dont know where the issue is even though i know what it is, might take a lil bit

**Comment by JoelZBub** [comment] 2022-02-06 14:14
This wasn't a very good issue report as it didn't include version numbers.
This Issue is relevant for Guard Villagers 1.0.1

This issue has been resolved with version 1.0.2
This should be marked closed.

**Closed** 2022-02-06 19:01 UTC
