### ISSUE TITLE
Crashing on game startup.

### ISSUE THREAD

**Issue by jwjones35** [mrsterner/GuardVillagers#62] opened 2023-04-12 03:38 UTC
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-04-11 22:33:12
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'guardvillagers'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: eu/midnightdust/lib/config/MidnightConfig
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at dev.mrsterner.guardvillagers.GuardVillagers.onInitialize(GuardVillagers.java:48)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: eu.midnightdust.lib.config.MidnightConfig
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 18 more

**Comment by BongoEADGC6** [comment] 2023-04-15 14:12
https://www.curseforge.com/minecraft/mc-mods/midnightlib/files/3496510

Ran into the same problem. This dependency is required in the newest version

**Comment by wither2123** [comment] 2023-04-18 05:02
> 

DUDE YOU ARE GOD, ty

**Comment by BongoEADGC6** [comment] 2023-04-19 18:19
Any time! In the future, this line here was the giveaway:
`Caused by: java.lang.ClassNotFoundException: eu.midnightdust.lib.config.MidnightConfig`

**Comment by mrsterner** [comment] 2023-05-03 13:27
Ill close the issue when ive added midnightlib to the fabric.mod.json dependencies

**Closed** 2023-07-22 07:06 UTC
